title: "Mohamed Aziz Maghrebi"
logo: img/MAGHREBI_MOHAMED_AZIZ.jpg
description: "Portfolio Quantitative Finance, Risk Modeling & Data Science"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
